# Generated by Django 2.2 on 2020-07-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='message',
            new_name='project_details',
        ),
    ]
