# Generated by Django 2.2 on 2020-07-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project_data', '0002_auto_20200730_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='contact_number',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='email_id',
            new_name='project_title',
        ),
    ]
