# Generated by Django 2.2 on 2020-07-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project_data', '0003_auto_20200730_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='pid',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='project_title',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='project_details',
            new_name='message',
        ),
    ]
