# Generated by Django 2.2 on 2020-07-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project_data', '0004_auto_20200730_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='email_id',
            new_name='pid',
        ),
    ]
