# Generated by Django 2.2 on 2020-07-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project_data', '0006_auto_20200730_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='message',
            new_name='project_description',
        ),
    ]
