# Generated by Django 2.2 on 2020-07-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project_data', '0008_auto_20200730_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Project Information', 'verbose_name_plural': 'Project Submission Data'},
        ),
    ]
